# Generated by Django 5.1.8 on 2025-05-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcespage",
            name="featured_whitepaper_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
